#!/usr/bin/node
// Send command to set the state of a circuit.
 
const ScreenLogic = require('./index');

var myArgs = process.argv.slice(2);
// use this to remote connect to a system by name (going through the Pentair servers)
const systemName = 'Pentair: '+ process.env.SYSTEMNAME;
const password = process.env.SYSTEMPASSWORD;
console.log('systemName: ' + systemName);
var remote = new ScreenLogic.RemoteLogin(systemName);
remote.on('gatewayFound', function(unit) {
  remote.close();
  if (unit && unit.gatewayFound) {
    console.log('unit ' + remote.systemName + ' found at ' + unit.ipAddr + ':' + unit.port);
    connect(new ScreenLogic.UnitConnection(unit.port, unit.ipAddr, password), parseInt(myArgs[0]), parseInt(myArgs[1]));
  } else {
    console.log('no unit found by that name');
  }
});

remote.connect();

function connect(client, poolOrSpa, level) {
  client.on('loggedIn', function() {
    this.getSaltCellConfig();
  }).on('saltCellConfig', function(saltCellConfig) {
    if(poolOrSpa == 0)
      this.setSaltCellOutput(0, level, saltCellConfig.level2);
    else
      this.setSaltCellOutput(0, saltCellConfig.level1, level);
    setTimeout(() => {  client.close(); }, 6000);        
  }).on('setSaltCellConfig', function(circuit) {
    client.close();
  }).on('error', function(err) {
   console.log(err);
  });

  client.connect();
}

