#!/usr/bin/node
// Send command to change state of Pool or Spa heater. Note: THIS WILL ALSO TURN POOL OR SPA ON.

const ScreenLogic = require('./index');

var myArgs = process.argv.slice(2);
// use this to remote connect to a system by name (going through the Pentair servers)
const systemName = 'Pentair: '+ process.env.SYSTEMNAME;
const password = process.env.SYSTEMPASSWORD;
console.log('systemName: ' + systemName);
var remote = new ScreenLogic.RemoteLogin(systemName);
remote.on('gatewayFound', function(unit) {
  remote.close();
  if (unit && unit.gatewayFound) {
    console.log('unit ' + remote.systemName + ' found at ' + unit.ipAddr + ':' + unit.port);
    connect(new ScreenLogic.UnitConnection(unit.port, unit.ipAddr, password), parseInt(myArgs[0]), parseInt(myArgs[1]));
  } else {
    console.log('no unit found by that name');
  }
});

remote.connect();

function connect(client, heater, onoff) {
  client.on('loggedIn', function() {
// Turn Heater for Pool or Spa on or Off.
  if (onoff == 1) {
    this.setHeatMode(0, heater, 3);
  }else if (onoff ==0) {
    this.setHeatMode(0, heater, 0);
  }
  }).on('heatModeChanged', function() {
    client.close();
  }).on('error', function(err) {
   console.log(err);
  }); ;

  client.connect();
}
