#!/usr/bin/node
// Send command to set the state of a circuit.
 
const ScreenLogic = require('./index');

var myArgs = process.argv.slice(2);
// use this to remote connect to a system by name (going through the Pentair servers)
const systemName = 'Pentair: '+ process.env.SYSTEMNAME;
const password = process.env.SYSTEMPASSWORD;
console.log('systemName: ' + systemName);
var remote = new ScreenLogic.RemoteLogin(systemName);
remote.on('gatewayFound', function(unit) {
  remote.close();
  if (unit && unit.gatewayFound) {
    console.log('unit ' + remote.systemName + ' found at ' + unit.ipAddr + ':' + unit.port);
    connect(new ScreenLogic.UnitConnection(unit.port, unit.ipAddr, password), parseInt(myArgs[0]), parseInt(myArgs[1]));
  } else {
    console.log('no unit found by that name');
  }
});

remote.connect();

function connect(client, circuit, onoff) {
  client.on('loggedIn', function() {
    console.log('login successful, setting circuit');
    async function setCircuit() { 
      await this.setCircuitState(0, circuit, onoff);
    }
    setCircuit().then(client.close());
    // setTimeout(() => {  client.close(); }, 5000);
     
  }).on('circuitStateChanged', function(circuit) {
    console.log('circuitId '+ circuit.circuitId + ' on controller ' + circuit.controllerId + ' changed to ' + circuit.circuitState);
  }).on('error', function(err) {
   console.log(err);
  }); 

  client.connect();
}

